sudo: required
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install boto3 black influxdb pyflakes
script:
  - pyflakes .
  - black --check .
  - make build
notifications:
  slack: exeum-foundation:N5NC7XlSG6BlY85rF3aILVG6
