version: '3'
services:
  okex-ltcbtc:
    image: exeum/antelope-scraper
    command: okex ltcbtc https://www.okex.com/api/v1/depth.do?symbol=ltc_btc
    volumes:
      - orderbooks:/orderbooks

  deliverer:
    image: exeum/antelope-deliverer
    volumes:
      - orderbooks:/orderbooks

volumes:
  orderbooks:
