version: '3'
services:
  gemini-btcusd:
    image: scraper
    command: gemini btcusd https://api.gemini.com/v1/book/btcusd
    volumes:
      - data:/root/data

  gemini-ethusd:
    image: scraper
    command: gemini ethusd https://api.gemini.com/v1/book/ethusd
    volumes:
      - data:/root/data

  gemini-ethbtc:
    image: scraper
    command: gemini ethbtc https://api.gemini.com/v1/book/ethbtc
    volumes:
      - data:/root/data

  bitfinex-btcusd:
    image: scraper
    command: bitfinex btcusd https://api.bitfinex.com/v1/book/btcusd --interval 3
    volumes:
      - data:/root/data

  okex-ltcbtc:
    image: scraper
    command: okex ltcbtc https://www.okex.com/api/v1/depth.do?symbol=ltc_btc
    volumes:
      - data:/root/data

  okex-ltceth:
    image: scraper
    command: okex ltceth https://www.okex.com/api/v1/depth.do?symbol=ltc_eth
    volumes:
      - data:/root/data

  binance-ltcbtc:
    image: scraper
    command: binance ltcbtc https://www.binance.com/api/v1/depth?symbol=LTCBTC
    volumes:
      - data:/root/data

  binance-ltceth:
    image: scraper
    command: binance ltceth https://www.binance.com/api/v1/depth?symbol=LTCETH
    volumes:
      - data:/root/data

  binance-ethbtc:
    image: scraper
    command: binance ethbtc https://www.binance.com/api/v1/depth?symbol=ETHBTC
    volumes:
      - data:/root/data

  deliverer:
    image: deliverer
    volumes:
      - data:/root/data

volumes:
  data:
