version: "3"
services:
  trades_bitfinex_btcusd:
    image: exeum/antelope-scraper
    command: trades bitfinex btc usd wss://api.bitfinex.com/ws --subscribe '{"event":"subscribe","channel":"trades","pair":"BTCUSD"}'
    volumes:
      - data:/data

  book_bitfinex_btcusd:
    image: exeum/antelope-scraper
    command: book bitfinex btc usd https://api.bitfinex.com/v1/book/btcusd --interval 6
    deploy:
      replicas: 2
    volumes:
      - data:/data

  trades_gdax_btcusd:
    image: exeum/antelope-scraper
    command: trades gdax btc usd wss://ws-feed.gdax.com --subscribe '{"type":"subscribe","product_ids":["BTC-USD"],"channels":["matches"]}'
    volumes:
      - data:/data

  book_gdax_btcusd:
    image: exeum/antelope-scraper
    command: book gdax btc usd https://api.gdax.com/products/BTC-USD/book?level=2 --interval 6
    deploy:
      replicas: 2
    volumes:
      - data:/data

volumes:
  data:
