version: "3"
services:
  bitfinex_book_btcusd:
    image: exeum/antelope-scraper
    command: bitfinex book btc usd wss://api.bitfinex.com/ws --subscribe '{"event":"subscribe","channel":"book","pair":"BTCUSD"}' --influxdb ${INFLUXDB}
    volumes:
      - data:/data

  bitfinex_trades_btcusd:
    image: exeum/antelope-scraper
    command: bitfinex trades btc usd wss://api.bitfinex.com/ws --subscribe '{"event":"subscribe","channel":"trades","pair":"BTCUSD"}' --influxdb ${INFLUXDB}
    volumes:
      - data:/data

  gdax_book_btcusd:
    image: exeum/antelope-scraper
    command: gdax book btc usd wss://ws-feed.gdax.com --subscribe '{"type":"subscribe","product_ids":["BTC-USD"],"channels":["level2"]}' --influxdb ${INFLUXDB}
    volumes:
      - data:/data

  gdax_trades_btcusd:
    image: exeum/antelope-scraper
    command: gdax trades btc usd wss://ws-feed.gdax.com --subscribe '{"type":"subscribe","product_ids":["BTC-USD"],"channels":["matches"]}' --influxdb ${INFLUXDB}
    volumes:
      - data:/data

  #gemini_book_btcusd:
  #  image: exeum/antelope-scraper
  #  command: gemini book btc usd wss://api.gemini.com/v1/marketdata/BTCUSD --influxdb ${INFLUXDB}
  #  volumes:
  #    - data:/data

  #gemini_trades_btcusd:
  #  image: exeum/antelope-scraper
  #  command: gemini trades btc usd wss://api.gemini.com/v1/marketdata/BTCUSD --influxdb ${INFLUXDB}
  #  volumes:
  #    - data:/data

  binance_book_ltcbtc:
    image: exeum/antelope-scraper
    command: binance book ltc btc wss://stream.binance.com:9443/ws/ltcbtc@depth --snapshot 'https://www.binance.com/api/v1/depth?symbol=LTCBTC' --influxdb ${INFLUXDB}
    volumes:
      - data:/data

  binance_trades_ltcbtc:
    image: exeum/antelope-scraper
    command: binance trades ltc btc wss://stream.binance.com:9443/ws/ltcbtc@trade --influxdb ${INFLUXDB}
    volumes:
      - data:/data

  deliverer:
    image: exeum/antelope-deliverer
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    deploy:
      mode: global
    volumes:
      - data:/data

volumes:
  data:
