version: "3"
services:
  trades_bitfinex_btcusd:
    image: exeum/antelope-scraper
    command: trades bitfinex btc usd wss://api.bitfinex.com/ws --subscribe '{"event":"subscribe","channel":"book","pair":"BTCUSD"}'
    volumes:
      - data:/data

  book_gdax_btcusd:
    image: exeum/antelope-scraper
    command: book gdax btc usd https://api.gdax.com/products/BTC-USD/book?level=2
    volumes:
      - data:/data

  book_gemini_btcusd:
    image: exeum/antelope-scraper
    command: book gemini btc usd https://api.gemini.com/v1/book/btcusd
    volumes:
      - data:/data

  book_bitfinex_btcusd:
    image: exeum/antelope-scraper
    command: book bitfinex btc usd https://api.bitfinex.com/v1/book/btcusd --interval 3
    volumes:
      - data:/data

  book_okex_ltcbtc:
    image: exeum/antelope-scraper
    command: book okex ltc btc https://www.okex.com/api/v1/depth.do?symbol=ltc_btc
    volumes:
      - data:/data

  book_binance_ltcbtc:
    image: exeum/antelope-scraper
    command: book binance ltc btc https://www.binance.com/api/v1/depth?symbol=LTCBTC
    volumes:
      - data:/data

  deliverer:
    image: exeum/antelope-deliverer
    volumes:
      - data:/data

volumes:
  data:
